connection: &connection
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  min_messages: warning
  username: postgres
  password: postgres

development:
  <<: *connection
  database: showscore_dev

test: &test
  <<: *connection
  database: showscore_test
